version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work

  web:
    build: ./infra/nginx
    ports:
      - 10080:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  php-fpm-socket:
  db-store: